"""Mock AI provider — deterministic canned completions for offline demos.

Selected with AI_PROVIDER=mock in .env. No network, no API key. Output is
derived from the issue lines embedded in the prompt so generated release notes
reflect the actually selected version. Swap to a real provider by setting
ANTHROPIC_API_KEY / OPENAI_API_KEY and removing AI_PROVIDER=mock.
"""

import re
import time


def _issues_in(prompt: str) -> list[tuple[str, str, str]]:
    """Extract ([KEY] Type … / Summary: …) pairs from a release-notes prompt."""
    out = []
    for m in re.finditer(
        r"\[([A-Z]+-\d+)\]\s+(\w+)[^\n]*\nSummary:\s*([^\n]+)", prompt
    ):
        out.append((m.group(1), m.group(2), m.group(3).strip()))
    return out


def _release_notes(prompt: str) -> str:
    issues = _issues_in(prompt)
    stories = [s for _, t, s in issues if t == "Story"]
    bugs = [s for _, t, s in issues if t == "Bug"]
    name_m = re.search(
        r"Release:\s*([^\n]+?)(?:\s{2,}Project:|$)", prompt, re.MULTILINE
    )
    version = name_m.group(1).strip() if name_m else "This release"

    headline = stories[0] if stories else (bugs[0] if bugs else "maintenance changes")
    short = f"{version} delivers {len(issues)} changes, headlined by “{headline}”."

    full_lines = [
        f"This release contains {len(stories)} improvements and {len(bugs)} fixes."
    ]
    if stories:
        full_lines.append(
            "Improvements: "
            + "; ".join(stories[:4])
            + ("…" if len(stories) > 4 else ".")
        )
    if bugs:
        full_lines.append(
            "Fixes: " + "; ".join(bugs[:4]) + ("…" if len(bugs) > 4 else ".")
        )

    biz = (
        "Shipping this batch reduces support load from known defects and unblocks "
        "the workflows above for end users; deferring it would carry the open bugs "
        "into the next cycle. (Generated by the mock AI provider — set a real API "
        "key for production-quality text.)"
    )

    return "\n".join(
        [
            "<<<SHORT_DESCRIPTION>>>",
            short,
            "<<<FULL_DESCRIPTION>>>",
            *full_lines,
            "<<<BUSINESS_JUSTIFICATION>>>",
            biz,
        ]
    )


def _generic(prompt: str) -> str:
    issues = _issues_in(prompt)
    if issues:
        return (
            f"Revised text covering {len(issues)} tickets, e.g. {issues[0][0]} "
            f"({issues[0][2]}). (Mock AI provider — deterministic placeholder.)"
        )
    return "Mock AI response. Set ANTHROPIC_API_KEY or OPENAI_API_KEY for real completions."


def _answer(messages: list) -> str:
    prompt = "\n".join(str(m.get("content", "")) for m in messages)
    if "<<<SHORT_DESCRIPTION>>>" in prompt:
        return _release_notes(prompt)
    return _generic(prompt)


def complete(
    config: dict, messages: list, system: str = None, max_tokens: int = 4096
) -> str:
    return _answer(messages)


def stream(config: dict, messages: list, system: str = None, max_tokens: int = 2048):
    for word in _answer(messages).split(" "):
        yield word + " "
        time.sleep(0.01)   # visible streaming in the UI


# ── Tool-use support ──────────────────────────────────────────────────────────

_MOCK_TOOL_SCRIPT = [
    # Turn 1: call grep to simulate a search
    {
        "stop_reason": "tool_use",
        "text":        "",
        "tool_calls":  [{"id": "mock_tc_1", "name": "grep",
                         "input": {"pattern": "onboarding", "glob": "silver/*.json"}}],
    },
    # Turn 2 (after receiving tool result): produce final answer
    {
        "stop_reason": "end_turn",
        "text": ("Based on the search results, there are several tickets related to onboarding. "
                 "The most recent is ADM-1000 (New onboarding flow for billing). "
                 "(Mock AI provider — set a real API key for production-quality answers.)"),
        "tool_calls": [],
    },
]

def complete_with_tools(config: dict, messages: list, tools: list,
                        system: str = None, max_tokens: int = 4096) -> dict:
    # Derive which script turn to use from message history length so the mock
    # is stateless — concurrent requests no longer race on a shared counter.
    # Turn 0: [user_question]  →  len=1
    # Turn 1: [user_q, asst, user_tool_results]  →  len=3
    turn = min((len(messages) - 1) // 2, len(_MOCK_TOOL_SCRIPT) - 1)
    # When tools=[] (force-final call), always return an end_turn text response.
    if not tools:
        turn = len(_MOCK_TOOL_SCRIPT) - 1
    entry = _MOCK_TOOL_SCRIPT[turn]

    content: list = []
    if entry["text"]:
        content.append({"type": "text", "text": entry["text"]})
    for tc in entry["tool_calls"]:
        content.append({"type": "tool_use", "id": tc["id"], "name": tc["name"],
                        "input": tc["input"]})

    return {
        "stop_reason": entry["stop_reason"],
        "content":     content,
        "text":        entry["text"],
        "tool_calls":  list(entry["tool_calls"]),
        "usage":       {"input_tokens": 10, "output_tokens": 20,
                        "cache_read_input_tokens": 0},
    }


def make_assistant_message(result: dict) -> dict:
    return {"role": "assistant", "content": result["content"]}


def make_tool_result_message(tool_results: list) -> list:
    blocks = [
        {"type": "tool_result", "tool_use_id": r["id"], "content": r["content"],
         **({"is_error": True} if r.get("is_error") else {})}
        for r in tool_results
    ]
    return [{"role": "user", "content": blocks}]
