"""Mock AI provider — deterministic canned completions for offline demos.

Selected with AI_PROVIDER=mock in .env. No network, no API key. Output is
derived from the issue lines embedded in the prompt so generated release notes
reflect the actually selected version. Swap to a real provider by setting
ANTHROPIC_API_KEY / OPENAI_API_KEY and removing AI_PROVIDER=mock.
"""

import re
import time


def _issues_in(prompt: str) -> list[tuple[str, str, str]]:
    """Extract ([KEY] Type … / Summary: …) pairs from a release-notes prompt."""
    out = []
    for m in re.finditer(r"\[([A-Z]+-\d+)\]\s+(\w+)[^\n]*\nSummary:\s*([^\n]+)", prompt):
        out.append((m.group(1), m.group(2), m.group(3).strip()))
    return out


def _release_notes(prompt: str) -> str:
    issues = _issues_in(prompt)
    stories = [s for _, t, s in issues if t == "Story"]
    bugs    = [s for _, t, s in issues if t == "Bug"]
    name_m  = re.search(r"Release:\s*([^\n]+?)(?:\s{2,}Project:|$)", prompt, re.MULTILINE)
    version = name_m.group(1).strip() if name_m else "This release"

    headline = stories[0] if stories else (bugs[0] if bugs else "maintenance changes")
    short = f"{version} delivers {len(issues)} changes, headlined by “{headline}”."

    full_lines = [f"This release contains {len(stories)} improvements and {len(bugs)} fixes."]
    if stories:
        full_lines.append("Improvements: " + "; ".join(stories[:4]) + ("…" if len(stories) > 4 else "."))
    if bugs:
        full_lines.append("Fixes: " + "; ".join(bugs[:4]) + ("…" if len(bugs) > 4 else "."))

    biz = ("Shipping this batch reduces support load from known defects and unblocks "
           "the workflows above for end users; deferring it would carry the open bugs "
           "into the next cycle. (Generated by the mock AI provider — set a real API "
           "key for production-quality text.)")

    return "\n".join([
        "<<<SHORT_DESCRIPTION>>>", short,
        "<<<FULL_DESCRIPTION>>>", *full_lines,
        "<<<BUSINESS_JUSTIFICATION>>>", biz,
    ])


def _generic(prompt: str) -> str:
    issues = _issues_in(prompt)
    if issues:
        return (f"Revised text covering {len(issues)} tickets, e.g. {issues[0][0]} "
                f"({issues[0][2]}). (Mock AI provider — deterministic placeholder.)")
    return "Mock AI response. Set ANTHROPIC_API_KEY or OPENAI_API_KEY for real completions."


def _answer(messages: list) -> str:
    prompt = "\n".join(str(m.get("content", "")) for m in messages)
    if "<<<SHORT_DESCRIPTION>>>" in prompt:
        return _release_notes(prompt)
    return _generic(prompt)


def complete(config: dict, messages: list, system: str = None, max_tokens: int = 4096) -> str:
    return _answer(messages)


def stream(config: dict, messages: list, system: str = None, max_tokens: int = 2048):
    for word in _answer(messages).split(" "):
        yield word + " "
        time.sleep(0.01)   # visible streaming in the UI
